### ISSUE TITLE
I don't think Faucet is working

### ISSUE THREAD

**Issue by haikukoten** [parsec-labs/parsec-faucet#13]
I made a token request on Dec 12 but I didn't receive any tokens. Though the request was accepted no tokens were dispensed to my wallet.

![Screenshot (799)](https://user-images.githubusercontent.com/24366687/70999934-65365e80-2100-11ea-86b0-dd920f01650f.png) **This the screenshot after I connected Metamask and requested again.**

Here's the Wallet Address - https://etherscan.io/address/0xb75eb924568d4ebf65d9bb932c589c3c06a59655#comments

Environment when I made the request:-
- Made from Mobile Phone
- Metamask wasn't connected then

**Comment by troggy** [comment]
thanks for reporting! Will be fixed

**Comment by troggy** [comment]
@saumyabratadutt it is actually working, you got 2 LEAP tokens on plasma. Check the explorer here:
https://mainnet.leapdao.org/explorer/address/0xb75eb924568d4ebf65d9bb932c589c3c06a59655
The faucet UI is not clear now — it sends tokens on plasma, not on the mainnet.
